name: TagGame
version: '${version}'
main: com.ryanlauderbach.taggame.TagGame
api-version: 1.19
author: Ryan
description: Play tag with your friends in Minecraft!

commands:
  tag-game:
    description: Command for configuring tag.