name: Tag
version: @version@
main: com.ryan.tag.Tag
api-version: 1.17
author: Ryan
description: Play tag with your friends in Minecraft!

commands:
  tag:
    description: Command for starting and stopping a game of tag.