main: com.rayn.tag.Main
name: Tag
version: "0.5"
author: Rayn
api-version: "1.13"

commands:
  tag:
    description: Command for starting and stopping a game of tag.
    permission: tag.startgame
    permission-message: You do not have permission!
permissions:
  tag.startgame:
    description: Allows the player to start a game.
    default: op